# Config file specifying the setup of a Triangular Residual Flow

data:
  n: 10000
  dim: 2

model:
  flow_layers: 64
  nn_layers: 2
  nn_hidden_units: 128

training:
  num_iter: 10000
  batch_size: 256
  lr: 1e-3
  jax_seed: 0
  np_seed: 0
  log_iter: 1000
  checkpoint_iter: 5000
  save_root: ./